// src/app/[lang]/page.tsx
import "server-only";

import Preview from "@/../public/room.png";
import { Button } from "@/components/Button";
import { GithubButton } from "@/components/GithubButton";
import LocaleSwitcher from "@/components/LocaleSwitcher";
import { ThemeSwitcher } from "@/components/ThemeSwitcher";
import type { I18nLocale } from "@/i18n/getDictionary";
import {
  getDictionary,
  getLanguageNames,
  i18nConfig,
} from "@/i18n/getDictionary";
import { usersService } from "@/server/services";
import { getSession } from "@/server/session";
import type { Room, User } from "@/types";
import { LinkIcon, RocketIcon } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { redirect, RedirectType } from "next/navigation";

type SearchParams = { [key: string]: string | string[] | undefined };

type Props = {
  params: Promise<{ lang: I18nLocale }>;
  searchParams: Promise<SearchParams>;
};

export default async function Home(props: Props) {
  const { lang } = await props.params;

  let { tab } = await props.searchParams;
  if (tab !== "create" && tab !== "join") {
    tab = "create";
  }

  const i18n = getDictionary(lang).pages.home;
  const session = await getSession();
  const { userId, roomSlug } = session;

  if (roomSlug && userId) {
    async function getData(
      roomSlug: string,
      userId: number
    ): Promise<{ user?: User; room?: Room }> {
      try {
        const result = await usersService.checkIfUserExistsInRoom(
          roomSlug,
          userId
        );
        return result;
      } catch (err) {
        console.error(err);
        return {};
      }
    }
    const { user, room } = await getData(roomSlug, userId);
    if (user && room) {
      redirect(`/${lang}/rooms/${roomSlug}`, RedirectType.replace);
    }
  }

  return (
    <div className="flex flex-col h-full grow">
      <header className="flex gap-2 py-2 px-4 justify-between">
        <div className="flex gap-2 items-center">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="28"
            height="28"
            viewBox="0 0 28 28"
            fill="none"
            stroke="#1a1d23"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <rect
              strokeWidth="0"
              x="0"
              y="0"
              width="28"
              height="28"
              rx="8"
              ry="8"
              fill="#35975c"
            />
            <g transform="translate(2,2)">
              <path d="M19 2v3h3" />
              <path d="M13.4 10.6 22 2" />
              <circle cx="12" cy="12" r="2" />
              <path d="M12.3 6H12a6 6 0 1 0 6 6v-.3" />
              <path d="M15 2.5A9.93 9.93 0 1 0 21.5 9" />
              <path d="M5.3 19.4 4 22" />
              <path d="M18.7 19.4 20 22" />
            </g>
          </svg>
          <div className="text-2xl">Aestimo</div>
        </div>
        <div className="flex gap-2 items-center">
          <LocaleSwitcher
            i18nConfig={i18nConfig}
            languageNames={getLanguageNames()}
          />
          <ThemeSwitcher />
          <GithubButton />
        </div>
      </header>
      <section className="grow w-full flex flex-col items-center justify-center px-6 py-16">
        <div className="max-w-6xl w-full grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
          <div className="text-center lg:text-left">
            <h1 className="text-4xl sm:text-5xl md:text-6xl font-extrabold text-foreground leading-tight mb-4">
              {i18n.header}
            </h1>

            <p className="text-lg sm:text-xl md:text-2xl text-muted-foreground mb-6">
              {i18n.subheader}
            </p>

            <ul className="space-y-3 text-base md:text-lg text-foreground mb-8">
              {i18n.advantages.map((advantage) => (
                <li key={advantage} className="flex items-center gap-2">
                  {advantage}
                </li>
              ))}
            </ul>

            <div className="flex flex-col sm:flex-row gap-4 justify-center lg:justify-start">
              <Link href="/new?tab=create">
                <Button variant="primary">
                  <RocketIcon />
                  {i18n.buttons.new}
                </Button>
              </Link>
              <Link href="/new?tab=join">
                <Button variant="secondary">
                  <LinkIcon />
                  {i18n.buttons.join}
                </Button>
              </Link>
            </div>
          </div>

          <div className="w-full flex justify-center">
            <Image
              src={Preview}
              alt="room"
              width={500}
              height={500}
              className="rounded-lg shadow-lg w-full max-w-[400px]"
            />
          </div>
        </div>
      </section>
    </div>
  );
}

// src/routes/[lang]/+page.svelte
<script>
	import { asset, resolve } from '$app/paths';
	import { page } from '$app/state';
	import ThemeSwitcher from '$lib/components/ThemeSwitcher.svelte';
	import { i18n } from '$lib/i18n/state.svelte';
	import { LinkIcon, RocketIcon } from '@lucide/svelte';
</script>

<div class="flex flex-col h-full grow">
	<header class="flex gap-2 p-4 justify-between items-center m-auto w-full xl:max-w-6xl">
		<a href={resolve('/')} class="flex gap-2 items-center">
			<img src={asset('/icon.svg')} alt="icon" width={32} height={32} />
			<div class="text-2xl">Aestimo</div>
		</a>
		<div class="flex gap-2 items-center">
			<ThemeSwitcher />
		</div>
	</header>
	<section
		class="grow w-full flex flex-col items-center justify-center px-6 py-16 xl:max-w-6xl m-auto"
	>
		<div class="max-w-6xl w-full grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
			<div class="text-center lg:text-left">
				<h1
					class="text-4xl sm:text-5xl md:text-6xl font-extrabold text-foreground leading-tight mb-4"
				>
					{i18n.messages.pages.home.header}
				</h1>

				<p class="text-lg sm:text-xl md:text-2xl text-muted-foreground mb-6">
					{i18n.messages.pages.home.subheader}
				</p>

				<div class="flex flex-col sm:flex-row gap-4 justify-center lg:justify-start">
					<a href={resolve(`/${page.params.lang}/new?tab=create`)}>
						<button>
							<RocketIcon />
							{i18n.messages.pages.home.buttons.new}
						</button>
					</a>
					<a href={resolve(`/${page.params.lang}/new?tab=join`)}>
						<button>
							<LinkIcon />
							{i18n.messages.pages.home.buttons.join}
						</button>
					</a>
				</div>
			</div>

			<div class="w-full flex justify-center">
				<img
					src={asset('/room.webp')}
					width={550}
					height={458}
					alt="room"
					class="rounded-lg shadow-lg w-full"
				/>
			</div>
		</div>
	</section>
</div>
