// src/routes/[lang]/rooms/[slug]/CardsHand.svelte
<script lang="ts">
	import type { ClientRoom, VoteCard } from '$lib/types';

	import { getContrastYIQ } from '$lib/utils/colors';

	interface Props {
		voteOptions: VoteCard[];
		room: ClientRoom;
		setVoted: () => void;
		selectedIndex: number | null;
	}

	let { voteOptions, room, setVoted, selectedIndex = $bindable() }: Props = $props();

	const roundFinished = $derived(room.status === 'finished');

	async function vote(index: number) {
		if (roundFinished || index === selectedIndex) {
			return;
		}

		try {
			const res = await fetch(`/api/rooms/${room.slug}/vote`, {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({ voteIndex: index })
			});

			const json: { success: boolean } = await res.json();

			if (res.ok && json.success) {
				setVoted();
				selectedIndex = index;
			}
		} catch (err) {
			console.error(err);
		}
	}
</script>

<div class="m-4 flex flex-wrap items-center justify-center gap-4 md:gap-6">
	{#each voteOptions as voteOption, index (voteOption.value)}
		<button
			class={[
				'cursor-pointer rounded-lg border-2 px-4 py-4 text-4xl font-bold shadow-md transition md:px-6 md:py-8',
				selectedIndex === index && '-translate-y-6 scale-110 border-card-foreground',
				roundFinished && 'cursor-not-allowed opacity-60'
			].join(' ')}
			style:background-color={voteOption.color}
			style:color={getContrastYIQ(voteOption.color)}
			style:border-color={selectedIndex === index ? 'var(--card-foreground)' : undefined}
			title={voteOption.value}
			onclick={() => vote(index)}
		>
			{voteOption.value}
		</button>
	{/each}
</div>

// src/app/[lang]/rooms/[roomSlug]/_components/CardsHand.tsx
"use client";

import type { ClientRoom, VoteCard } from "@/types";
import { api } from "@/utils/api";
import { cn } from "@/utils/cn";
import { getContrastYIQ } from "@/utils/colors";
import React from "react";

type Props = {
  voteOptions: VoteCard[];
  room: ClientRoom;
  setVoted: () => void;
  selectedIndex: number | null;
  setSelectedIndex: React.Dispatch<React.SetStateAction<number | null>>;
};

const CardsHand: React.FC<Props> = ({
  voteOptions,
  room,
  setVoted,
  selectedIndex,
  setSelectedIndex,
}) => {
  const roundFinished: boolean = room.status === "finished";

  const onClick = async (index: number) => {
    if (roundFinished) return;
    if (index === selectedIndex) return;
    try {
      const body = { voteIndex: index };
      const res = await api.post(`/api/rooms/${room.slug}/vote`, body);
      const json: { success: boolean } = await res.json();
      if (res.ok && json.success) {
        setVoted();
        setSelectedIndex(index);
      }
    } catch (err) {
      console.error(err);
    }
  };

  return (
    <div className="flex justify-center items-center gap-4 md:gap-6 flex-wrap m-4">
      {voteOptions.map((voteOption, index) => {
        const { color, value } = voteOption;
        const selected: boolean = index === selectedIndex;
        const style: React.CSSProperties = {
          backgroundColor: color,
          color: getContrastYIQ(color),
        };
        if (selected) {
          style.borderColor = "var(--card-foreground)";
        }
        return (
          <div
            key={value}
            className={cn(
              "px-4 py-4 border-2 rounded-lg cursor-pointer font-bold text-4xl shadow-md transition text-black md:px-6 md:py-8 ",
              selected ? "-translate-y-6 scale-110 border-2" : "",
              roundFinished ? "opacity-60 cursor-not-allowed" : ""
            )}
            title={value}
            style={style}
            onClick={() => onClick(index)}
          >
            {value}
          </div>
        );
      })}
    </div>
  );
};

export default CardsHand;
