// src/app/rooms/[roomUUID]/_components/CardsHand.tsx
"use client";

import { VoteCard } from "@/backend/types";
import { api } from "@/lib/api";
import { cn } from "@/lib/utils";
import React, { useState } from "react";

type Props = {
  cards: VoteCard[];
  roomUUID: string;
  userId: number;
  setVoted: (voted: boolean) => void;
  initialSelectedIndex: number | null;
};

const CardsHand: React.FC<Props> = ({
  cards,
  roomUUID,
  setVoted,
  initialSelectedIndex,
}) => {
  const [selectedIndex, setSelectedIndex] = useState<number | null>(
    initialSelectedIndex
  );

  const onClick = async (index: number) => {
    if (index === selectedIndex) return;

    try {
      const body = { voteIndex: index };
      const res = await api.post(`/api/rooms/${roomUUID}/vote`, body);
      const json: { success: boolean } = await res.json();
      if (json.success) {
        setVoted(true);
        setSelectedIndex(index);
      }
    } catch (err) {
      console.error(err);
    }
  };

  return (
    <div className="flex justify-center items-center gap-4 flex-wrap m-auto">
      {cards.map((card, index) => {
        const { color, value } = card;
        const selected: boolean = index === selectedIndex;
        const style: React.CSSProperties = { backgroundColor: color };
        if (selected) {
          style.borderColor = "var(--card-foreground)";
          style.borderWidth = "2px";
        }
        return (
          <div
            key={value}
            className={cn(
              "px-6 py-8 border-2 rounded-lg cursor-pointer font-bold text-4xl shadow-md transition",
              selected ? "-translate-y-4" : ""
            )}
            title={value}
            style={style}
            onClick={() => onClick(index)}
          >
            {value}
          </div>
        );
      })}
    </div>
  );
};

export default CardsHand;

// src/routes/[lang]/rooms/[slug]/CardsHand.svelte
<script lang="ts">
	import type { ClientRoom, VoteCard } from '$lib/types';

	import { getContrastYIQ } from '$lib/utils/colors';

	interface Props {
		voteOptions: VoteCard[];
		room: ClientRoom;
		setVoted: () => void;
		selectedIndex: number | null;
	}

	let { voteOptions, room, setVoted, selectedIndex = $bindable() }: Props = $props();

	const roundFinished = $derived(room.status === 'finished');

	async function vote(index: number) {
		if (roundFinished || index === selectedIndex) {
			return;
		}

		try {
			const res = await fetch(`/api/rooms/${room.slug}/vote`, {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({ voteIndex: index })
			});

			const json: { success: boolean } = await res.json();

			if (res.ok && json.success) {
				setVoted();
				selectedIndex = index;
			}
		} catch (err) {
			console.error(err);
		}
	}
</script>

<div class="m-4 flex flex-wrap items-center justify-center gap-4 md:gap-6">
	{#each voteOptions as voteOption, index (voteOption.value)}
		<button
			class={[
				'cursor-pointer rounded-lg border-2 px-4 py-4 text-4xl font-bold shadow-md transition md:px-6 md:py-8',
				selectedIndex === index && '-translate-y-6 scale-110 border-card-foreground',
				roundFinished && 'cursor-not-allowed opacity-60'
			].join(' ')}
			style:background-color={voteOption.color}
			style:color={getContrastYIQ(voteOption.color)}
			style:border-color={selectedIndex === index ? 'var(--card-foreground)' : undefined}
			title={voteOption.value}
			onclick={() => vote(index)}
		>
			{voteOption.value}
		</button>
	{/each}
</div>
