// src/app/[lang]/rooms/[roomUUID]/_components/Toolbar/index.tsx
"use client";

import { Button } from "@/components/Button";
import type { Dictionary } from "@/i18n/getDictionary";
import type { ClientRoom, ClientUser } from "@/types";
import type { NextRoundEvent, RestartEvent } from "@/types/EventData";
import { api } from "@/utils/api";
import { ArrowRightCircleIcon, EyeIcon, RotateCwIcon } from "lucide-react";
import React, { useState } from "react";
import { DeleteButton } from "./DeleteButton";
import styles from "./Toolbar.module.css";

type ToolbarProps = {
  room: ClientRoom;
  i18n: Dictionary["pages"]["room"]["toolbar"];
  revealVotes: (data: ClientUser[]) => void;
  restartRound: (data: RestartEvent["data"]) => void;
  goToNextRound: (data: NextRoundEvent["data"]) => void;
};

const Toolbar: React.FC<ToolbarProps> = ({
  room,
  i18n,
  revealVotes,
  restartRound,
  goToNextRound,
}) => {
  const [loadingButton, setLoadingButton] = useState<
    "reveal" | "next" | "restart" | null
  >(null);

  async function onClickReveal() {
    if (loadingButton) return;
    setLoadingButton("reveal");
    try {
      const res = await api.post(`/api/rooms/${room.uuid}/reveal`);
      const data: ClientUser[] = await res.json();
      revealVotes(data);
    } catch (err) {
      console.error(err);
    }
    setLoadingButton(null);
  }

  async function onClickNextRound() {
    if (loadingButton) return;
    setLoadingButton("next");
    try {
      const res = await api.post(`/api/rooms/${room.uuid}/next`, {});
      const data: NextRoundEvent["data"] = await res.json();
      goToNextRound(data);
    } catch (err) {
      console.error(err);
    }
    setLoadingButton(null);
  }

  async function onClickRestart() {
    if (loadingButton) return;
    setLoadingButton("restart");
    try {
      const res = await api.post(`/api/rooms/${room.uuid}/restart`);
      const data: RestartEvent["data"] = await res.json();
      restartRound(data);
    } catch (err) {
      console.error(err);
    }
    setLoadingButton(null);
  }

  return (
    <div className={styles.toolbar}>
      {room.status !== "finished" && (
        <Button onClick={onClickReveal} loading={loadingButton === "reveal"}>
          <EyeIcon />
          {i18n.reveal}
        </Button>
      )}

      {room.status === "finished" && (
        <Button onClick={onClickNextRound} loading={loadingButton === "next"}>
          <ArrowRightCircleIcon />
          {i18n.next}
        </Button>
      )}

      <Button onClick={onClickRestart} loading={loadingButton === "restart"}>
        <RotateCwIcon />
        {i18n.restart}
      </Button>

      <DeleteButton room={room} i18n={i18n["delete-modal"]} />
    </div>
  );
};

export { Toolbar };

// src/routes/[lang]/rooms/[slug]/Toolbar.svelte
<script lang="ts">
	import type { Dictionary } from '$lib/i18n';
	import type { ClientRoom, ClientUser } from '$lib/types';
	import type { NextRoundEvent, RestartEvent } from '$lib/types/EventData';
	import ArrowRightCircleIcon from '@lucide/svelte/icons/arrow-right-circle';
	import EyeIcon from '@lucide/svelte/icons/eye';
	import RotateCwIcon from '@lucide/svelte/icons/rotate-cw';

	interface Props {
		room: ClientRoom;
		i18n: Dictionary['pages']['room']['toolbar'];
		revealVotes: (data: ClientUser[]) => void;
		restartRound: (data: RestartEvent['data']) => void;
		goToNextRound: (data: NextRoundEvent['data']) => void;
	}

	let { room, i18n, revealVotes, restartRound, goToNextRound }: Props = $props();

	let loadingButton = $state<'reveal' | 'next' | 'restart' | null>(null);

	async function execute<T>(
		action: 'reveal' | 'next' | 'restart',
		url: string,
		callback: (data: T) => void
	) {
		if (loadingButton) return;

		loadingButton = action;

		try {
			const res = await fetch(url, { method: 'POST' });
			const data = (await res.json()) as T;

			callback(data);
		} catch (err) {
			console.error(err);
		} finally {
			loadingButton = null;
		}
	}
</script>

<div class="toolbar">
	{#if room.status !== 'finished' && !room.autoreveal}
		<button
			onclick={() => execute<ClientUser[]>('reveal', `/api/rooms/${room.slug}/reveal`, revealVotes)}
			disabled={loadingButton === 'reveal'}
		>
			<EyeIcon />
			{i18n.reveal}
		</button>
	{/if}

	{#if room.status === 'finished'}
		<button
			onclick={() =>
				execute<NextRoundEvent['data']>('next', `/api/rooms/${room.slug}/next`, goToNextRound)}
			disabled={loadingButton === 'next'}
		>
			<ArrowRightCircleIcon />
			{i18n.next}
		</button>
	{/if}

	{#if room.status !== 'finished'}
		<button
			onclick={() =>
				execute<RestartEvent['data']>('restart', `/api/rooms/${room.slug}/restart`, restartRound)}
			disabled={loadingButton === 'restart'}
		>
			<RotateCwIcon />
			{i18n.restart}
		</button>
	{/if}
</div>
