// src/routes/[lang]/rooms/[slug]/Toolbar.svelte
<script lang="ts">
	import type { Dictionary } from '$lib/i18n';
	import type { ClientRoom, ClientUser } from '$lib/types';
	import type { NextRoundEvent, RestartEvent } from '$lib/types/EventData';
	import ArrowRightCircleIcon from '@lucide/svelte/icons/arrow-right-circle';
	import EyeIcon from '@lucide/svelte/icons/eye';
	import RotateCwIcon from '@lucide/svelte/icons/rotate-cw';

	interface Props {
		room: ClientRoom;
		i18n: Dictionary['pages']['room']['toolbar'];
		revealVotes: (data: ClientUser[]) => void;
		restartRound: (data: RestartEvent['data']) => void;
		goToNextRound: (data: NextRoundEvent['data']) => void;
	}

	let { room, i18n, revealVotes, restartRound, goToNextRound }: Props = $props();

	let loadingButton = $state<'reveal' | 'next' | 'restart' | null>(null);

	async function execute<T>(
		action: 'reveal' | 'next' | 'restart',
		url: string,
		callback: (data: T) => void
	) {
		if (loadingButton) return;

		loadingButton = action;

		try {
			const res = await fetch(url, { method: 'POST' });
			const data = (await res.json()) as T;

			callback(data);
		} catch (err) {
			console.error(err);
		} finally {
			loadingButton = null;
		}
	}
</script>

<div class="toolbar">
	{#if room.status !== 'finished' && !room.autoreveal}
		<button
			class="btn"
			onclick={() => execute<ClientUser[]>('reveal', `/api/rooms/${room.slug}/reveal`, revealVotes)}
			disabled={loadingButton === 'reveal'}
		>
			<EyeIcon />
			{i18n.reveal}
		</button>
	{/if}

	{#if room.status === 'finished'}
		<button
			class="btn"
			onclick={() =>
				execute<NextRoundEvent['data']>('next', `/api/rooms/${room.slug}/next`, goToNextRound)}
			disabled={loadingButton === 'next'}
		>
			<ArrowRightCircleIcon />
			{i18n.next}
		</button>
	{/if}

	{#if room.status !== 'finished'}
		<button
			class="btn"
			onclick={() =>
				execute<RestartEvent['data']>('restart', `/api/rooms/${room.slug}/restart`, restartRound)}
			disabled={loadingButton === 'restart'}
		>
			<RotateCwIcon />
			{i18n.restart}
		</button>
	{/if}
</div>

// src/app/rooms/[roomUUID]/_components/Toolbar/index.tsx
"use client";

import { ClientRoom, ClientUser } from "@/backend/types";
import { api } from "@/lib/api";
import { EyeIcon, RotateCcwIcon, Trash2Icon } from "lucide-react";
import { useRouter } from "next/navigation";
import React from "react";
import styles from "./Toolbar.module.css";

type Props = {
  roomUUID: string;
  i18n: {
    reveal: string;
    delete: string;
    restart: string;
    leave: string;
    invite: string;
    history: string;
  };
  setRoom: React.Dispatch<React.SetStateAction<ClientRoom>>;
  setUsersList: React.Dispatch<React.SetStateAction<ClientUser[]>>;
};

const Toolbar: React.FC<Props> = ({
  roomUUID,
  i18n,
  setRoom,
  setUsersList,
}) => {
  const router = useRouter();

  async function onClickRestart() {
    try {
      const res = await api.post(`/api/rooms/${roomUUID}/restart`);
      const { room }: { room: ClientRoom } = await res.json();
      setRoom(room);
    } catch (err) {
      console.error(err);
    }
  }

  async function onClickReveal() {
    try {
      const res = await api.post(`/api/rooms/${roomUUID}/reveal`);
      const json: ClientUser[] = await res.json();
      setUsersList(json);
    } catch (err) {
      console.error(err);
    }
  }

  async function onClickDelete() {
    try {
      const res = await api.post(`/api/rooms/${roomUUID}`);
      if (res.ok) router.replace("/");
    } catch (err) {
      console.error(err);
    }
  }

  return (
    <div className={styles.toolbarWrapper}>
      <div className={styles.toolbar}>
        <button className="btn" onClick={onClickReveal}>
          <EyeIcon />
          {i18n.reveal}
        </button>
        <button className="btn" onClick={onClickRestart}>
          <RotateCcwIcon />
          {i18n.restart}
        </button>
        <button className="btn" onClick={onClickDelete}>
          <Trash2Icon />
          {i18n.delete}
        </button>
      </div>
    </div>
  );
};

export { Toolbar };
