// src/components/widgets/CreateRoomForm.tsx
"use client";

import type { DefinedVoteType } from "@/backend/consts/predefinedVoteTypes";
import { Button } from "@/components/Button";
import { Input } from "@/components/Input";
import type { Dictionary } from "@/i18n/get-dictionary";
import { api } from "@/utils/api";
import { Loader2Icon } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { Switch } from "../Switch";

type Response = { roomUUID: string };

type Props = {
  i18n: Dictionary["createRoomForm"];
  predefinedVoteTypes: DefinedVoteType[];
};

const CreateRoomForm: React.FC<Props> = ({ i18n, predefinedVoteTypes }) => {
  const router = useRouter();
  const [loading, setLoading] = useState<boolean>(false);
  const [name, setName] = useState<string>("");
  const [username, setUsername] = useState<string>("");
  const [privateRoom, setPrivateRoom] = useState<boolean>(false);
  const [voteTypeId, setVoteTypeIdId] = useState<string>(
    predefinedVoteTypes[0].id
  );

  const getLabel = (option: DefinedVoteType): string => {
    return `${option.name} (${option.values.map((o) => o.value).join(", ")})`;
  };

  const onFinish = async () => {
    setLoading(true);
    try {
      const options = predefinedVoteTypes.find(
        (option) => option.id === voteTypeId
      );

      if (options) {
        const values = {
          name,
          username,
          voteOptions: options?.values,
          private: privateRoom,
        };

        const res = await api.post("/api/rooms", values);
        if (res.ok) {
          const { roomUUID }: Response = await res.json();
          router.replace(`/rooms/${roomUUID}`);
        }
      }
    } catch (err) {
      console.error(err);
    }

    setLoading(false);
  };

  return (
    <div>
      <div className="px-6 py-3">
        <h1 className="text-center font-semibold text-lg">{i18n.header}</h1>
      </div>
      <hr className="w-full" />
      <form className="flex flex-col px-6 pb-6 pt-3 grow">
        <div className="grow">
          <Input
            type="text"
            name="name"
            label={i18n.roomName}
            onChange={(e) => setName(e.target.value)}
          />
          <Input
            type="text"
            name="username"
            label={i18n.username}
            onChange={(e) => setUsername(e.target.value)}
          />
          <div className="flex items-center gap-2 mb-3">
            <Switch
              id="private"
              onCheckedChange={(value) => {
                setPrivateRoom(value);
              }}
              checked={privateRoom}
            />
            <label htmlFor="private">{i18n.private}</label>
          </div>
          <fieldset className="flex flex-col gap-1">
            <legend className="font-semibold mb-1">{i18n.checkboxes}</legend>
            {predefinedVoteTypes.map((option) => (
              <div className="flex gap-2" key={option.id}>
                <input
                  type="radio"
                  id={option.id}
                  name="voteType"
                  value={option.id}
                  checked={option.id === voteTypeId}
                  onChange={(e) => {
                    const id = e.target.value;
                    setVoteTypeIdId(id);
                  }}
                />
                <label htmlFor={option.id}>{getLabel(option)}</label>
              </div>
            ))}
          </fieldset>
        </div>
        <Button
          variant="primary"
          className="mt-4"
          onClick={onFinish}
          type="button"
          disabled={loading}
        >
          {loading && (
            <Loader2Icon className="animate-spin" width={20} height={20} />
          )}
          {i18n.create}
        </Button>
      </form>
    </div>
  );
};

export { CreateRoomForm };

// src/routes/[lang]/new/CreateRoomForm.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { resolve } from '$app/paths';
	import { page } from '$app/state';
	import Button from '$lib/components/Button.svelte';
	import Input from '$lib/components/Input.svelte';
	import RadioButton from '$lib/components/RadioButton.svelte';
	import SmallVoteCard from '$lib/components/SmallVoteCard.svelte';
	import Switch from '$lib/components/Switch.svelte';
	import { i18n as locales } from '$lib/i18n/state.svelte';
	import type { DefinedVoteType } from '$lib/server/consts/predefinedVoteTypes';
	import { slugify } from '$lib/utils/slugify';
	import { LoaderCircleIcon } from '@lucide/svelte';

	type Props = {
		predefinedVoteTypes: DefinedVoteType[];
	};
	const { predefinedVoteTypes }: Props = $props();

	const i18n = locales.messages.pages.new.createRoomForm;
	let loading = $state<boolean>(false);
	let userVoteTypeId = $state<string | null>(null);
	let voteTypeId = $derived(userVoteTypeId ?? predefinedVoteTypes[0].id);
	let prefix = $state<string>('');

	const renderSlugHelper = (): string => {
		if (!prefix.length) {
			return i18n.slug.random;
		}
		const url: string = `${location.origin}/${slugify(prefix)}-xxxxxxx`;
		return `${i18n.slug.helper} ${url}`;
	};

	const onSubmit = async (e: SubmitEvent) => {
		e.preventDefault();
		loading = true;

		const form = e.target as HTMLFormElement;
		const data = new FormData(form);

		const voteType = predefinedVoteTypes.find((voteType) => voteType.id === voteTypeId);
		const body = {
			name: data.get('name') as string,
			username: data.get('username') as string,
			prefix: data.get('prefix') as string,
			private: data.has('private'),
			voteOptions: voteType?.values
		};

		const res = await fetch('/api/rooms', {
			method: 'POST',
			headers: { 'Content-Type': 'application/json' },
			body: JSON.stringify(body)
		});

		if (res.ok) {
			const room: { slug: string } = await res.json();
			const url = resolve(`/${page.params.lang}/rooms/${room.slug}`);
			await goto(url);
		}
		loading = false;
	};
</script>

<div>
	<div class="px-6 py-3">
		<h1 class="text-center font-semibold text-lg">{i18n.header}</h1>
	</div>
	<hr class="w-full" />
	<form class="flex flex-col px-6 pb-6 pt-3 grow" onsubmit={onSubmit}>
		<div class="grow">
			<Input name="name" label={i18n.roomName} required />
			<Input type="text" name="username" label={i18n.username} required />
			<Input
				type="text"
				name="prefix"
				label={i18n.slug.label}
				helper={renderSlugHelper()}
				bind:value={prefix}
			/>
			<div class="flex items-center gap-2 mb-3">
				<Switch name="private" id="private" />
				<label for="private">{i18n.private.label}</label>
			</div>
			<fieldset class="flex flex-col gap-4 mt-8 mb-8">
				<legend class="font-semibold mb-3">
					<span>{i18n.checkboxes}</span>
					<span class="text-(--color-destructive)"> *</span>
				</legend>
				{#each predefinedVoteTypes as option (option.id)}
					<div class="flex gap-2 items-center">
						<RadioButton
							id={option.id}
							name="voteType"
							value={option.id}
							checked={option.id === voteTypeId}
							onChange={() => (userVoteTypeId = option.id)}
						>
							<b class="min-w-32">{option.name}</b>
							<div class="flex gap-0.5 flex-wrap">
								{#each option.values as card (card.value)}
									<SmallVoteCard {...card} />
								{/each}
							</div>
						</RadioButton>
					</div>
				{/each}
			</fieldset>
		</div>
		<Button>
			{#if loading}
				<LoaderCircleIcon class="animate-spin" size={20} />
			{/if}
			{i18n.create}
		</Button>
	</form>
</div>
