// src/components/widgets/JoinRoomForm.tsx
"use client";

import { Button } from "@/components/Button";
import { Input } from "@/components/Input";
import type { Dictionary } from "@/i18n/getDictionary";
import { api } from "@/utils/api";
import { Loader2Icon } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { toast, Toaster } from "sonner";

type Props = {
  i18n: Dictionary["pages"]["new"]["joinRoomForm"];
  roomSlug: string;
};

const JoinRoomForm: React.FC<Props> = ({ i18n, roomSlug }) => {
  const router = useRouter();
  const [loading, setLoading] = useState<boolean>(false);
  const [username, setUsername] = useState<string>("");

  const onFinish = async () => {
    setLoading(true);
    try {
      const res = await api.post(`/api/rooms/${roomSlug}/join`, { username });
      if (res.ok) {
        router.replace(`/rooms/${roomSlug}`);
      } else {
        const data = await res.json();
        console.log(data);
        toast.error(data.error);
      }
    } catch (err) {
      console.error(err);
    }
    setLoading(false);
  };

  return (
    <form className="flex flex-col px-6 pb-6 pt-3 grow">
      <Toaster richColors />
      <div className="grow">
        <Input
          id="username"
          type="text"
          label={i18n.username}
          value={username}
          onChange={(e) => setUsername(e.target.value)}
        />
      </div>
      <Button
        variant="primary"
        type="button"
        className="mt-4"
        onClick={onFinish}
        disabled={loading}
      >
        {loading && <Loader2Icon className="animate-spin" size={20} />}
        {i18n.join}
      </Button>
    </form>
  );
};

export { JoinRoomForm };

// src/routes/[lang]/new/JoinRoomForm.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { toast } from 'svelte-sonner';

	import Input from '$lib/components/Input.svelte';
	import { api } from '$lib/utils/api';

	import { LoaderCircleIcon } from '@lucide/svelte';

	import type { Dictionary } from '$lib/i18n/index';

	interface Props {
		i18n: Dictionary['pages']['new']['joinRoomForm'];
		roomSlug: string;
	}

	let { i18n, roomSlug }: Props = $props();

	let loading = $state(false);
	let username = $state('');

	async function onFinish(e: SubmitEvent) {
		e.preventDefault();
		loading = true;

		try {
			const res = await api.post(`/api/rooms/${roomSlug}/join`, {
				username
			});

			if (res.ok) {
				await goto(`/rooms/${roomSlug}`, {
					replaceState: true
				});
			} else {
				const data = await res.json();
				toast.error(data.error);
			}
		} catch (err) {
			console.error(err);
		} finally {
			loading = false;
		}
	}
</script>

<form class="flex grow flex-col px-6 pt-3 pb-6" onsubmit={onFinish}>
	<div class="grow">
		<Input id="username" label={i18n.username} bind:value={username} />
	</div>

	<button type="submit" class="mt-4" disabled={loading}>
		{#if loading}
			<LoaderCircleIcon class="animate-spin" size={20} />
		{/if}

		{i18n.join}
	</button>
</form>
