// src/components/widgets/PublicRoomsList/index.tsx
import "server-only";

import type { Dictionary, I18nLocale } from "@/i18n/getDictionary";
import { roomsService } from "@/server/services";
import type { ClientRoom } from "@/types";
import { DoorClosedIcon, DoorOpenIcon, SearchXIcon } from "lucide-react";
import Link from "next/link";
import styles from "./PublicRoomsList.module.css";

type Props = {
  lang: I18nLocale;
  i18n: Dictionary["pages"]["new"]["joinRoomForm"];
};

const PublicRoomsList: React.FC<Props> = async ({ lang, i18n }) => {
  const roomsToJoin: ClientRoom[] = await roomsService.getPublicRooms();

  function renderRoomsList() {
    if (roomsToJoin.length === 0) {
      return (
        <div className={styles.empty}>
          <SearchXIcon size={32} />
          <h5>{i18n.empty}</h5>
        </div>
      );
    }

    return (
      <ul className="flex flex-col">
        {roomsToJoin.map((room) => (
          <Link href={`/${lang}/rooms/${room.slug}/join`} key={room.slug}>
            <li className={styles.roomItem}>
              <div className={styles.icon}>
                <DoorClosedIcon />
                <DoorOpenIcon />
              </div>
              <div className={styles.roomName}>{room.name}</div>
            </li>
          </Link>
        ))}
      </ul>
    );
  }

  return (
    <div>
      <div className="px-6 py-3">
        <h1 className="text-center font-semibold text-lg">{i18n.header}</h1>
      </div>
      <hr className="w-full" />
      {renderRoomsList()}
    </div>
  );
};

export { PublicRoomsList };

// src/routes/[lang]/new/PublicRoomsList.svelte
<script lang="ts">
	import { resolve } from '$app/paths';
	import type { Dictionary } from '$lib/i18n';
	import type { ClientRoom } from '$lib/types';

	import { DoorClosedIcon, DoorOpenIcon, SearchXIcon } from '@lucide/svelte';

	type Props = {
		rooms: ClientRoom[];
		i18n: Dictionary['pages']['new']['joinRoomForm'];
	};
	let { i18n, rooms }: Props = $props();

	function getHref(room: ClientRoom) {
		return resolve('/rooms/[slug]/join', { slug: room.slug });
	}
</script>

{#if rooms.length === 0}
	<div class="empty">
		<SearchXIcon size={32} />
		<h5>{i18n.empty}</h5>
	</div>
{:else}
	<ul class="flex flex-col">
		{#each rooms as room (room.slug)}
			<li>
				<a href={getHref(room)} class="roomItem">
					<div class="icon">
						<div class="doorOpenIcon">
							<DoorOpenIcon />
						</div>
						<div class="doorClosedIcon">
							<DoorClosedIcon />
						</div>
					</div>

					<div class="roomName">
						{room.name}
					</div>
				</a>
			</li>
		{/each}
	</ul>
{/if}

<style>
	.roomItem {
		padding: 8px 16px;
		cursor: pointer;
		display: flex;
		align-items: center;
		border-bottom: 1px solid var(--color-border);
		gap: 8px;
	}

	.roomItem:hover .roomName {
		text-decoration: underline;
	}

	.roomItem .icon .doorOpenIcon {
		display: none;
	}

	.roomItem:hover .doorClosedIcon {
		display: none;
	}

	.roomItem:hover .icon .doorOpenIcon {
		display: block;
	}

	.empty {
		padding: 24px;
		display: flex;
		flex-direction: column;
		gap: 12px;
		align-items: center;
		text-align: center;
		color: var(--color-muted-foreground);
	}
</style>
