// src/lib/components/VoteTypeCreator.svelte
<script lang="ts">
	import ColorPicker from '$lib/components/ColorPicker.svelte';
	import type { Dictionary } from '$lib/i18n';
	import type { VoteCard } from '$lib/types';
	import { getContrastYIQ, getRandomPresetColor } from '$lib/utils/colors';
	import PlusCircleIcon from '@lucide/svelte/icons/plus-circle';
	import Trash2Icon from '@lucide/svelte/icons/trash-2';

	export type CustomVoteCard = VoteCard & {
		id: number;
	};

	let {
		cards = $bindable(),
		i18n
	}: {
		cards: CustomVoteCard[];
		i18n: Dictionary['pages']['new']['createRoomForm']['customVoteCard'];
	} = $props();

	function addCard() {
		const max = Math.max(0, ...cards.map((c) => c.id));

		cards = [
			...cards,
			{
				id: max + 1,
				color: getRandomPresetColor(),
				value: String(cards.length + 1)
			}
		];
	}

	function deleteCard(id: number) {
		cards = cards.filter((card) => card.id !== id);
	}
</script>

<div class="flex flex-wrap items-center gap-0.5 mt-3">
	{#each cards as card (card.id)}
		<div
			class="voteCard"
			style:background-color={card.color}
			style:color={getContrastYIQ(card.color)}
		>
			<input id={`vote_${card.id}`} size="1" bind:value={card.value} />

			<button
				type="button"
				class="deleteButton"
				title={i18n.delete}
				onclick={() => deleteCard(card.id)}
			>
				<Trash2Icon size={14} />
			</button>

			<ColorPicker bind:hex={card.color} />
		</div>
	{/each}

	<button class="addButton" type="button" onclick={addCard}>
		<PlusCircleIcon size={20} />
	</button>
</div>

<style>
	.voteCard {
		border-width: 1px;
		border-radius: var(--radius);
		font-weight: 600;
		min-width: 60px;
		padding: 24px 8px;
		background-color: transparent;
		color: black;
		position: relative;
		display: flex;
		align-items: center;
		justify-content: center;
		position: relative;
	}

	.voteCard input {
		width: min-content;
		text-align: center;
		border: 0px;
	}

	.voteCard input:focus {
		outline: 0px;
	}

	.voteCard input:active {
		border: 0px;
		outline: none;
	}

	.addButton {
		display: flex;
		align-items: center;
		justify-content: center;
		cursor: pointer;
		font-weight: 600;
		min-width: 60px;
		height: 74px;
		border-width: 1px;
		border-radius: var(--radius);
	}

	.addButton:hover {
		color: var(--primary);
	}

	.deleteButton {
		border-radius: var(--radius);
		padding: 4px;
		cursor: pointer;
	}

	.deleteButton {
		position: absolute;
		top: 0px;
		right: 0px;
	}
</style>

// src/components/widgets/CreateRoomForm/VoteTypeCreator/index.tsx
"use client";

import { Dictionary } from "@/i18n/getDictionary";
import type { VoteCard } from "@/types";
import { getContrastYIQ } from "@/utils/colors";
import { PaintBucketIcon, PlusCircleIcon, Trash2Icon } from "lucide-react";
import { useState } from "react";
import { ColorPicker } from "../ColorPicker";
import { getRandomPresetColor } from "../ColorPicker/colors";
import styles from "./VoteTypeCreator.module.css";

export type CustomVoteCard = VoteCard & { id: number };

type Props = {
  cards: CustomVoteCard[];
  onChange: (newValues: CustomVoteCard[]) => void;
  i18n: Dictionary["pages"]["new"]["createRoomForm"]["customVoteCard"];
};

const VoteTypeCreator: React.FC<Props> = ({ cards, onChange, i18n }) => {
  const [colorPickerShownIndex, setColorPickerShownIndex] = useState<
    number | null
  >(null);

  function renderAddButton() {
    return (
      <div
        className={styles.addButton}
        onClick={() => {
          let max = Math.max(...cards.map((card) => card.id));
          if (!isFinite(max)) max = 0;

          onChange([
            ...cards,
            {
              id: max + 1,
              color: getRandomPresetColor(),
              value: `${cards.length + 1}`,
            },
          ]);
        }}
      >
        <PlusCircleIcon size={20} />
      </div>
    );
  }

  function renderCard(card: CustomVoteCard, index: number) {
    const { id, color, value } = card;
    const textColor = getContrastYIQ(color);

    return (
      <div
        className={styles.voteCard}
        key={id}
        style={{ backgroundColor: color, color: textColor }}
      >
        <input
          size={1}
          id={`vote_${id}`}
          value={value}
          onChange={(e) => {
            e.preventDefault();
            const value = e.currentTarget.value;
            const newCards = [...cards];
            newCards[index].value = value;
            onChange(newCards);
          }}
        />
        <button type="button" className={styles.paintButton} title={i18n.color}>
          <PaintBucketIcon
            size={14}
            onClick={() => setColorPickerShownIndex(index)}
          />
        </button>
        <button
          type="button"
          className={styles.deleteButton}
          onClick={(e) => {
            e.preventDefault();
            const newCards = cards.filter((card) => card.id !== id);
            onChange(newCards);
          }}
          title={i18n.delete}
        >
          <Trash2Icon size={14} />
        </button>

        <ColorPicker
          opened={index === colorPickerShownIndex}
          setClose={() => setColorPickerShownIndex(null)}
          color={color}
          onChange={(newColor) => {
            const newCards = [...cards];
            newCards[index].color = newColor;
            onChange(newCards);
          }}
        />
      </div>
    );
  }

  return (
    <div className="flex gap-0.5 flex-wrap items-center mt-3">
      {cards.map((card, index) => renderCard(card, index))}
      {renderAddButton()}
    </div>
  );
};

export { VoteTypeCreator };
