// src/components/Input.tsx
import React from "react";

import { cn } from "@/utils/cn";

const Input = React.forwardRef<
  HTMLInputElement,
  React.ComponentProps<"input"> & { label: string; helper?: string }
>(({ label, helper, className, type, ...props }, ref) => {
  return (
    <div className="space-y-1 flex flex-col mb-3">
      <label htmlFor={props.id}>{label}</label>
      <input
        id={props.id}
        type={type}
        className={cn(
          className,
          "flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-base shadow-sm transition-colors file:border-0 file:bg-transparent file:text-sm file:font-medium file:text-foreground placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50 md:text-sm"
        )}
        ref={ref}
        {...props}
      />
      {helper && (
        <span className="text-[var(--muted-foreground)]">{helper}</span>
      )}
    </div>
  );
});
Input.displayName = "Input";

export { Input };

// src/lib/components/Input.svelte
<script lang="ts">
	import type { HTMLInputAttributes } from 'svelte/elements';

	interface Props extends HTMLInputAttributes {
		label: string;
		helper?: string;
		class?: string;
	}

	let {
		label,
		helper,
		class: className = '',
		value = $bindable(),
		id,
		type = 'text',
		...rest
	}: Props = $props();
</script>

<div class="mb-3 flex flex-col space-y-1">
	<label for={id}>{label}</label>

	<input
		bind:value
		{id}
		{type}
		class={`flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-base shadow-sm transition-colors placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50 md:text-sm ${className}`}
		{...rest}
	/>

	{#if helper}
		<span class="text-(--muted-foreground)">
			{helper}
		</span>
	{/if}
</div>
