// src/components/Switch.tsx
"use client";

import * as RadixSwitch from "@radix-ui/react-switch";
import React from "react";

import { cn } from "@/utils/cn";

const Switch = React.forwardRef<
  React.ComponentRef<typeof RadixSwitch.Root>,
  React.ComponentPropsWithoutRef<typeof RadixSwitch.Root>
>(({ className, ...props }, ref) => (
  <RadixSwitch.Root
    className={cn(
      "peer inline-flex h-5 w-9 shrink-0 cursor-pointer items-center rounded-full border-2 border-transparent shadow-sm transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=unchecked]:bg-input",
      className
    )}
    {...props}
    ref={ref}
  >
    <RadixSwitch.Thumb
      className={cn(
        "pointer-events-none block h-4 w-4 rounded-full bg-background shadow-lg ring-0 transition-transform data-[state=checked]:translate-x-4 data-[state=unchecked]:translate-x-0"
      )}
    />
  </RadixSwitch.Root>
));
Switch.displayName = RadixSwitch.Root.displayName;

export { Switch };

// src/lib/components/Switch.svelte
<script lang="ts">
	type Props = {
		id?: string;
		checked?: boolean;
		disabled?: boolean;
		onChange?: (value: boolean) => void;
	};
	let { disabled, id, checked, onChange }: Props = $props();
</script>

<label class="switchContainer" class:disabled>
	<input
		{id}
		type="checkbox"
		{checked}
		{disabled}
		onchange={(event) => {
			if (onChange) onChange(!!event.currentTarget.checked);
		}}
	/>
	<span class="switchSlider"></span>
</label>

<style>
	.switchContainer {
		position: relative;
		display: inline-block;
		min-width: 42px;
		height: 24px;
		cursor: pointer;
	}

	.switchContainer input {
		opacity: 0;
		width: 0;
		height: 0;
	}

	.switchSlider {
		position: absolute;
		inset: 0;
		background-color: var(--background);
		border-width: 1px;
		border-radius: 9999px;
		transition: background-color 0.2s;
	}

	.switchSlider::before {
		content: '';
		position: absolute;
		left: 3px;
		top: 3px;
		height: 16px;
		width: 16px;
		background-color: var(--foreground);
		border-radius: 9999px;
		transition: transform 0.2s;
		box-shadow: 0 1px 2px rgba(0, 0, 0, 0.1);
	}

	.switchContainer input:checked + .switchSlider {
		background-color: var(--primary);
	}

	.switchContainer input:checked + .switchSlider::before {
		transform: translateX(18px);
		background-color: var(--primary-foreground);
	}

	.switchContainer input:focus-visible + .switchSlider {
		outline: 2px solid var(--ring);
		outline-offset: 2px;
	}

	.switchContainer.disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}
</style>
