// src/components/ThemeSwitcher.tsx
"use client";

import { Button } from "@/components/Button";
import { MoonIcon, SunIcon } from "lucide-react";
import { useTheme } from "next-themes";
import React from "react";

const ThemeSwitcher: React.FC = () => {
  const { theme, setTheme } = useTheme();

  const toggleTheme = () => {
    const newTheme = theme === "light" ? "dark" : "light";
    setTheme(newTheme);
  };

  return (
    <Button variant="secondary" size="icon" onClick={toggleTheme}>
      <SunIcon className="h-[1.2rem] w-[1.2rem] scale-100 rotate-0 transition-all dark:scale-0 dark:-rotate-90" />
      <MoonIcon className="absolute h-[1.2rem] w-[1.2rem] scale-0 rotate-90 transition-all dark:scale-100 dark:rotate-0" />
    </Button>
  );
};

export { ThemeSwitcher };

// src/lib/components/ThemeSwitcher.svelte
<script lang="ts">
	import { getPreferredTheme, setTheme, type Theme } from '$lib/theme';
	import { MoonIcon, SunIcon } from '@lucide/svelte';

	let theme: Theme = $state('light');

	$effect(() => {
		theme = getPreferredTheme();
		setTheme(theme);
	});

	function toggleTheme() {
		theme = theme === 'light' ? 'dark' : 'light';
		setTheme(theme);
	}
</script>

<button onclick={toggleTheme} class="relative">
	<SunIcon
		class="h-[1.2rem] w-[1.2rem] transition-all duration-300 {theme === 'dark' ? 'scale-0 -rotate-90' : 'scale-100 rotate-0'}"
	/>
	<MoonIcon
		class="absolute left-0 top-0 h-[1.2rem] w-[1.2rem] transition-all duration-300 {theme === 'dark' ? 'scale-100 rotate-0' : 'scale-0 rotate-90'}"
	/>
</button>
